# encoding: UTF-8

FROM <%= ENV.fetch('FROM') %>
MAINTAINER The Blue Beluga <admin@bluebeluga.io>

LABEL name="openvpn"
LABEL description="Alpine Linux Base with OpenVPN Client."
LABEL git_revision="<%= ENV.fetch('GIT_REVISION') %>"

RUN apt-get update && \
    apt-get install -y openvpn iptables git-core netmask && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Update checkout to use tags when v3.0 is finally released
RUN git clone --depth 1 --branch v3.0.0-rc2 https://github.com/OpenVPN/easy-rsa.git /usr/local/share/easy-rsa && \
    ln -s /usr/local/share/easy-rsa/easyrsa3/easyrsa /usr/local/bin

ENV OPENVPN /etc/openvpn
ENV EASYRSA /usr/local/share/easy-rsa/easyrsa3
ENV EASYRSA_PKI $OPENVPN/pki
ENV EASYRSA_VARS_FILE $OPENVPN/vars

VOLUME ["/etc/openvpn"]

# Internally uses port 1194, remap using docker
EXPOSE 1194/udp

WORKDIR /etc/openvpn

CMD ["start_vpn.sh"]

ADD files/bin /usr/local/bin
RUN chmod a+x /usr/local/bin/*
